import moment from 'moment';

export const chatList = [
  {
    key: 1,
    name: 'Ronald Richards',
    lastMsg: 'So, what’s your plan this weekend?',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().format('LT'),
    profileView: true,
  },
  {
    key: 2,
    name: 'Jane Cooper',
    lastMsg: 'I hope it goes well.',
    img: require('../../../Assets/Images/man.png'),
    time: moment().format('LT'),
    profileView: true,
  },
  {
    key: 3,
    name: 'Annette Black',
    lastMsg: 'What’s the progress on that task?',
    img: require('../../../Assets/Images/photo(1).jpg'),
    time: moment().subtract(1, 'days').calendar({
      lastDay: '[Yesterday]',
    }),
    profileView: true,
  },
  {
    key: 4,
    name: 'Robert Fox',
    lastMsg: 'IDK what else is there to do',
    img: require('../../../Assets/Images/photo(2).jpg'),
    time: moment().format('dddd'),
    profileView: true,
  },
  {
    key: 5,
    name: 'Ronald Richards',
    lastMsg: 'So, what’s your plan this weekend?',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().subtract(1, 'days').format('dddd'),
    profileView: true,
  },
  {
    key: 6,
    name: 'Jane Cooper',
    lastMsg: 'I hope it goes well.',
    img: require('../../../Assets/Images/man.png'),
    time: moment().subtract(2, 'days').format('dddd'),
    profileView: true,
  },
  {
    key: 7,
    name: 'Annette Black',
    lastMsg: 'What’s the progress on that task?',
    img: require('../../../Assets/Images/photo(3).jpg'),
    time: moment().subtract(3, 'days').format('DD/MM/YY'),
    profileView: true,
  },
  {
    key: 8,
    name: 'Robert Fox',
    lastMsg: 'IDK what else is there to do',
    img: require('../../../Assets/Images/photo(4).jpg'),
    time: moment().subtract(4, 'days').format('DD/MM/YY'),
    profileView: true,
  },
  {
    key: 9,
    name: 'Robert Fox',
    lastMsg: 'IDK what else is there to do',
    img: require('../../../Assets/Images/photo(5).jpg'),
    time: moment().subtract(5, 'days').format('DD/MM/YY'),
    profileView: true,
  },
  {
    key: 10,
    name: 'Ronald Richards',
    lastMsg: 'So, what’s your plan this weekend?',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().subtract(6, 'days').format('DD/MM/YY'),
    profileView: true,
  },
  {
    key: 11,
    name: 'Jane Cooper',
    lastMsg: 'I hope it goes well.',
    img: require('../../../Assets/Images/man.png'),
    time: moment().subtract(8, 'days').format('DD/MM/YY'),
    profileView: true,
  },
  {
    key: 12,
    name: 'Annette Black',
    lastMsg: 'What’s the progress on that task?',
    img: require('../../../Assets/Images/photo(6).jpg'),
    time: moment().subtract(9, 'days').format('DD/MM/YY'),
    profileView: true,
  },
  {
    key: 13,
    name: 'Robert Fox',
    lastMsg: 'IDK what else is there to do',
    img: require('../../../Assets/Images/photo(2).jpg'),
    time: moment().subtract(10, 'days').format('DD/MM/YY'),
    profileView: true,
  },
];

export const recentChatList = [
  {
    key: 1,
    name: 'Ronald Richards',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().format('LT'),
    callStatus: 'Missed',
    callingType: 'audio',
  },
  {
    key: 2,
    name: 'Jane Cooper',
    img: require('../../../Assets/Images/man.png'),
    time: moment().format('LT'),
    callStatus: 'Incoming',
    callingType: 'video',
  },
  {
    key: 3,
    name: 'Annette Black',
    img: require('../../../Assets/Images/photo(1).jpg'),
    time: moment().subtract(1, 'days').calendar({
      lastDay: '[Yesterday]',
    }),
    callStatus: 'Outgoing',
    callingType: 'audio',
  },
  {
    key: 4,
    name: 'Robert Fox',
    img: require('../../../Assets/Images/photo(2).jpg'),
    time: moment().format('dddd'),
    callStatus: 'Incoming',
    callingType: 'video',
  },
  {
    key: 5,
    name: 'Ronald Richards',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().subtract(1, 'days').format('dddd'),
    callStatus: 'Outgoing',
    callingType: 'audio',
  },
  {
    key: 6,
    name: 'Jane Cooper',
    img: require('../../../Assets/Images/man.png'),
    time: moment().subtract(2, 'days').format('dddd'),
    callStatus: 'Missed',
    callingType: 'audio',
  },
  {
    key: 7,
    name: 'Annette Black',
    img: require('../../../Assets/Images/photo(3).jpg'),
    time: moment().subtract(3, 'days').format('DD/MM/YY'),
    callStatus: 'Incoming',
    callingType: 'audio',
  },
  {
    key: 8,
    name: 'Robert Fox',
    img: require('../../../Assets/Images/photo(4).jpg'),
    time: moment().subtract(4, 'days').format('DD/MM/YY'),
    callStatus: 'Missed',
    callingType: 'video',
  },
  {
    key: 9,
    name: 'Robert Fox',
    img: require('../../../Assets/Images/photo(5).jpg'),
    time: moment().subtract(5, 'days').format('DD/MM/YY'),
    callStatus: 'Missed',
    callingType: 'audio',
  },
  {
    key: 10,
    name: 'Ronald Richards',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().subtract(6, 'days').format('DD/MM/YY'),
    callStatus: 'Missed',
    callingType: 'audio',
  },
  {
    key: 11,
    name: 'Jane Cooper',
    img: require('../../../Assets/Images/man.png'),
    time: moment().subtract(8, 'days').format('DD/MM/YY'),
    callStatus: 'Missed',
    callingType: 'audio',
  },
  {
    key: 12,
    name: 'Annette Black',
    img: require('../../../Assets/Images/photo(6).jpg'),
    time: moment().subtract(9, 'days').format('DD/MM/YY'),
    callStatus: 'Missed',
    callingType: 'audio',
  },
  {
    key: 13,
    name: 'Robert Fox',
    img: require('../../../Assets/Images/photo(2).jpg'),
    time: moment().subtract(10, 'days').format('DD/MM/YY'),
    callStatus: 'Missed',
    callingType: 'audio',
  },
];

export const callList = [
  {
    key: 1,
    name: 'Ronald Richards',
    status: 'Busy',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().format('LT'),
  },
  {
    key: 2,
    name: 'Jane Cooper',
    status: 'Available',
    img: require('../../../Assets/Images/man.png'),
    time: moment().format('LT'),
  },
  {
    key: 3,
    name: 'Annette Black',
    status: 'Busy',
    img: require('../../../Assets/Images/photo(1).jpg'),
    time: moment().subtract(1, 'days').calendar({
      lastDay: '[Yesterday]',
    }),
  },
  {
    key: 4,
    name: 'Robert Fox',
    status: 'Love is in the air.',
    img: require('../../../Assets/Images/photo(2).jpg'),
    time: moment().format('dddd'),
  },
  {
    key: 5,
    name: 'Ronald Richards',
    status: 'SLive, Laugh & Stay Calm',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().subtract(1, 'days').format('dddd'),
  },
  {
    key: 6,
    name: 'Jane Cooper',
    status: 'I hope it goes well.',
    img: require('../../../Assets/Images/man.png'),
    time: moment().subtract(2, 'days').format('dddd'),
  },
  {
    key: 7,
    name: 'Annette Black',
    status: 'Lorem Ipson',
    img: require('../../../Assets/Images/photo(3).jpg'),
    time: moment().subtract(3, 'days').format('DD/MM/YY'),
  },
  {
    key: 8,
    name: 'Robert Fox',
    status: 'Lorem Ipson',
    img: require('../../../Assets/Images/photo(4).jpg'),
    time: moment().subtract(4, 'days').format('DD/MM/YY'),
  },
  {
    key: 9,
    name: 'Robert Fox',
    status: 'Lorem Ipson',
    img: require('../../../Assets/Images/photo(5).jpg'),
    time: moment().subtract(5, 'days').format('DD/MM/YY'),
  },
  {
    key: 10,
    name: 'Ronald Richards',
    status: 'Lorem Ipson',
    img: require('../../../Assets/Images/girl.png'),
    time: moment().subtract(6, 'days').format('DD/MM/YY'),
  },
  {
    key: 11,
    name: 'Jane Cooper',
    status: 'Lorem Ipson',
    img: require('../../../Assets/Images/man.png'),
    time: moment().subtract(8, 'days').format('DD/MM/YY'),
  },
  {
    key: 12,
    name: 'Annette Black',
    status: 'Lorem Ipson',
    img: require('../../../Assets/Images/photo(6).jpg'),
    time: moment().subtract(9, 'days').format('DD/MM/YY'),
  },
  {
    key: 13,
    name: 'Robert Fox',
    status: 'Lorem Ipson',
    img: require('../../../Assets/Images/photo(2).jpg'),
    time: moment().subtract(10, 'days').format('DD/MM/YY'),
  },
];
