export const GET_LANGUAGE_ACTION = 'GET_LANGUAGE_ACTION';
export const GET_LANGUAGE_SUCCESS_ACTION = 'GET_LANGUAGE_SUCCESS_ACTION';
export const CLAIM_FREE_CARD = 'CLAIM_FREE_CARD';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION';
export const GET_USER_STATS = 'GET_USER_STATS';

export const USER_REGISTRATION = 'USER_REGISTRATION';

export const FORGOT_PASSWORD_SEND_OTP_ACTION =
  'FORGOT_PASSWORD_SEND_OTP_ACTION';

export const FORGOT_PASSWORD_ACTION = 'FORGOT_PASSWORD_ACTION';

export const SENT_OTP = 'SENT_OTP';

export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const LOGOUT_SUCCESS_ACTION = 'LOGOUT_SUCCESS_ACTION';

export const SOCIAL_LOGIN_TYPE = 'SOCIAL_LOGIN_TYPE';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS_ACTION =
  'UPDATE_USER_PROFILE_SUCCESS_ACTION';
export const VIDEO_UPLOAD_ACTION = 'VIDEO_UPLOAD_ACTION';
export const IMAGE_UPLOAD_ACTION = 'IMAGE_UPLOAD_ACTION';
export const DELETE_IMAGE_VIDEO_ACTION = 'DELETE_IMAGE_VIDEO_ACTION';
export const GET_LIVE_USER_LIST_ACTION = 'GET_LIVE_USER_LIST_ACTION';

export const GET_INTEREST_LIST = 'GET_INTEREST_LIST';
export const GO_LIVE_STREAMING = 'GO_LIVE_STREAMING';
export const END_LIVE_STREAMING = 'END_LIVE_STREAMING';
export const GET_GIFT_DATA = 'GET_GIFT_DATA';
export const JOIN_USER_DATA_ON_LIVE_STREAM = 'JOIN_USER_DATA_ON_LIVE_STREAM';
export const COMMENT_ON_LIVE_STREAM = 'COMMENT_ON_LIVE_STREAM';
export const LIKE_LIVE_STREAM = 'LIKE_LIVE_STREAM';
export const UPDATE_LIKED_STATUS_ON_STREAM = 'UPDATE_LIKED_STATUS_ON_STREAM';
export const SEND_GIFT_ACTION = 'SEND_GIFT_ACTION';
export const REFRESH_DATA_ACTION = 'REFRESH_DATA_ACTION';
export const HOST_USER_DETAIL_ACTION = 'HOST_USER_DETAIL_ACTION';
export const UPDATE_HOST_POINTS_ACTION = 'UPDATE_HOST_POINTS_ACTION';
export const JOIN_USER_LIVE_STREAM = 'JOIN_USER_LIVE_STREAM';
export const GET_JOIN_USER_LIST = 'GET_JOIN_USER_LIST';
export const SAVE_JOIN_USER_LIST_DATA = 'SAVE_JOIN_USER_LIST_DATA';
export const CLEAR_LIVE_STREAM_DATA_ACTION = 'CLEAR_LIVE_STREAM_DATA_ACTION';
export const ACTIVE_LIVE_USERS_IN_STREAMING_ACTION =
  'ACTIVE_LIVE_USERS_IN_STREAMING_ACTION';
export const JOIN_NEW_USER_ACTION = 'JOIN_NEW_USER_ACTION';
export const LIKE_LIVE_STREAM_API = 'LIKE_LIVE_STREAM_API';
export const CHANGE_ANIMATION_TYPE = 'CHANGE_ANIMATION_TYPE';
export const CLEAR_JOINED_USER_LIST_ACTION = 'CLEAR_JOINED_USER_LIST_ACTION';
export const GET_HOST_EXTRA_DETAIL_ACTION = 'GET_HOST_EXTRA_DETAIL_ACTION';
export const GET_HOST_EXTRA_DETAIL_SUCCESS_ACTION =
  'GET_HOST_EXTRA_DETAIL_SUCCESS_ACTION';
export const AGORA_INITIALISED_ACTION = 'AGORA_INITIALISED_ACTION';
export const JOIN_HOST_PEER_ID_ACTION = 'JOIN_HOST_PEER_ID_ACTION';
export const JOIN_AUDIENCE_PEER_ID_ACTION = 'JOIN_AUDIENCE_PEER_ID_ACTION';
export const UPDATE_CALL_PEER_ID_ACTION = 'UPDATE_CALL_PEER_ID_ACTION';
export const INCOMING_CALL_POPUP_ACTION = 'INCOMING_CALL_POPUP_ACTION';
export const IS_LIVE_ACTIVE_ACTION = 'IS_LIVE_ACTIVE_ACTION';
export const INCOMING_CALL_POPUP_DATA_ACTION =
  'INCOMING_CALL_POPUP_DATA_ACTION';
export const GET_CALLING_DETAIL_ACTION = 'GET_CALLING_DETAIL_ACTION';
export const LEAVE_CALLING_ROOM_ACTION = 'LEAVE_CALLING_ROOM_ACTION';
export const CREATE_INCOME_CALL_ACTION = 'CREATE_INCOME_CALL_ACTION';
export const SHOW_GIFTS_ON_CALL_ACTION = 'SHOW_GIFTS_ON_CALL_ACTION';
export const FOLLOW_USER_ACTION = 'FOLLOW_USER_ACTION';

export const GET_FOLLOWER_LIST_ACTION = 'GET_FOLLOWER_LIST_ACTION';
export const GET_FOLLOWING_LIST_ACTION = 'GET_FOLLOWING_LIST_ACTION';
export const GET_FRIENDS_LIST_ACTION = 'GET_FRIENDS_LIST_ACTION';

export const GET_VISITOR_LIST_ACTION = 'GET_VISITOR_LIST_ACTION';
export const GET_RECENT_CHAT_LIST_ACTION = 'GET_RECENT_CHAT_LIST_ACTION';

export const CHECK_USER_TRADE_EXISTING_ACTION =
  'CHECK_USER_TRADE_EXISTING_ACTION';
export const TRADE_TRANSACTION_INITIALIZER = 'TRADE_TRANSACTION_INITIALIZER';
export const GET_TRADE_LIST_ACTION = 'GET_TRADE_LIST_ACTION';
export const GET_TRADE_TRANSFER = 'GET_TRADE_TRANSFER';
export const DELETE_RECENT_CALL_ACTION = 'DELETE_RECENT_CALL_ACTION';
export const VIEWED_PROFILE_USER_ACTION = 'VIEWED_PROFILE_USER_ACTION';
export const DELETE_ALL_RECENT_CALL_ACTION = 'DELETE_ALL_RECENT_CALL_ACTION';
export const CREATE_CHAT_ROOM_ACTION = 'CREATE_CHAT_ROOM_ACTION';
export const GET_CHAT_HISTORY_ACTION = 'GET_CHAT_HISTORY_ACTION';
export const GET_CHAT_HISTORY_SUCCESS_ACTION =
  'GET_CHAT_HISTORY_SUCCESS_ACTION';
export const APPEND_SOCKET_CHAT_DATA_ACTION = 'APPEND_SOCKET_CHAT_DATA_ACTION';
export const UPDATE_CHAT_HISTORY_ACTION = 'UPDATE_CHAT_HISTORY_ACTION';
export const GET_CHAT_LIST_ACTION = 'GET_CHAT_LIST_ACTION';
export const FOLLOWING_LIST_MODAL_ACTION = 'FOLLOWING_LIST_MODAL_ACTION';
export const DELETE_RECENT_CHAT_MODAL_ACTION =
  'DELETE_RECENT_CHAT_MODAL_ACTION';
export const UPLOAD_CHAT_MEDIA_FILE_ACTION = 'UPLOAD_CHAT_MEDIA_FILE_ACTION';
export const UPLOAD_CHAT_VIDEO_FILE_ACTION = 'UPLOAD_CHAT_VIDEO_FILE_ACTION';
export const GET_DIAMOND_LIST_ACTION = 'GET_DIAMOND_LIST_ACTION';
export const GET_AGENCY_LIST_ACTION = 'GET_AGENCY_LIST_ACTION';
export const LIVE_USER_MUTE = 'LIVE_USER_MUTE';
export const LIVE_USER_KICKOUT = 'LIVE_USER_KICKOUT';
export const LIVE_USER_BLOCK = 'LIVE_USER_BLOCK';
export const UNBLOCK_USER = 'UNBLOCK_USER';
export const MAKE_USER_ADMIN = 'MAKE_USER_ADMIN';
export const LIVE_USER_MUTE_FLAG = 'LIVE_USER_MUTE_FLAG';
export const REPORT_USER = 'REPORT_USER';
export const GET_GALLERY_LIST = 'GET_GALLERY_LIST';
export const ANOTHER_USER_PROFILE = 'ANOTHER_USER_PROFILE';
export const GET_VIDEO_LIST = 'GET_VIDEO_LIST';
export const GET_USER_EARNING = 'GET_USER_EARNING';
export const GET_FREE_CARDS = 'GET_FREE_CARDS';
export const DELETE_ONE_MSG = 'DELETE_ONE_MSG';
export const UPDATE_CHAT_AFTER_DEL_ONE_MESSAGE =
  'UPDATE_CHAT_AFTER_DEL_ONE_MESSAGE';
export const UPDATE_CLEAR_CHAT_FLAG = 'UPDATE_CLEAR_CHAT_FLAG';
export const UPDATE_SELECT_ALL_CHAT = 'UPDATE_SELECT_ALL_CHAT';
export const UPDATE_DELETE_CHAT = 'UPDATE_DELETE_CHAT';
export const DELETE_SELECTED_CHAT = 'DELETE_SELECTED_CHAT';
export const LIVE_SESSION_USER_BLOCK = 'LIVE_SESSION_USER_BLOCK';
export const GET_USER_EARNING_DETAIL = 'GET_USER_EARNING_DETAIL';
export const GET_USER_SETTLEMENT_DETAIL = 'GET_USER_SETTLEMENT_DETAIL';
export const GET_BLOCK_LIST = 'GET_BLOCK_LIST';
export const LINK_MAIL = 'LINK_MAIL';
export const LINK_PHONE = 'LINK_PHONE';
export const UPDATE_MAIL = 'UPDATE_MAIL';
export const UPDATE_PHONE = 'UPDATE_PHONE';
export const GET_HELP_CENTER = 'GET_HELP_CENTER';
export const PUT_IN_KICKOUT_ROOM = 'PUT_IN_KICKOUT_ROOM';
export const PUT_IN_BLOCK_ROOM = 'PUT_IN_BLOCK_ROOM';
export const GRP_CHAT_CREATION = 'GRP_CHAT_CREATION';
export const GET_GROUP_CHATS = 'GET_GROUP_CHATS';
export const INVITE_TO_GROUP = 'INVITE_TO_GROUP';
export const ALLOW_FREE_CHAT = 'ALLOW_FREE_CHAT';
export const SHARE_LIVE_LINK_IN_CHAT = 'SHARE_LIVE_LINK_IN_CHAT';
export const GET_GRP_DETAILS = 'GET_GRP_DETAILS';
export const MAKE_GRP_ADMIN = 'MAKE_GRP_ADMIN';
export const REMOVE_GRP_MEMBER = 'REMOVE_GRP_MEMBER';
export const GET_GROUP_CHAT_HISTORY_ACTION = 'GET_GROUP_CHAT_HISTORY_ACTION';
export const UPDATE_GRP_CHAT_HISTORY_ACTION = 'UPDATE_GRP_CHAT_HISTORY_ACTION';
export const GET_GROUP_CHAT_HISTORY_SUCCESS_ACTION =
  'GET_GROUP_CHAT_HISTORY_SUCCESS_ACTION';
export const APPEND_SOCKET_GRP_CHAT_DATA_ACTION =
  'APPEND_SOCKET_GRP_CHAT_DATA_ACTION';
export const GRP_CHAT_UPDATE = 'GRP_CHAT_UPDATE';
export const REMOVE_USER_LIVE_STREAM = 'REMOVE_USER_LIVE_STREAM';
export const COMMENT_ON_CALL = 'COMMENT_ON_CALL';
export const CLEAR_COMMENT_ON_CALL = 'CLEAR_COMMENT_ON_CALL';

export const GET_USER_AGREEMENT = 'GET_USER_AGREEMENT';
export const GET_ABOUT_WEECHA = 'GET_ABOUT_WEECHA';
export const GET_PRIVACY_POLICY = 'GET_PRIVACY_POLICY';

export const GET_SEARCH_USER = 'GET_SEARCH_USER';
export const GET_WEECHA_LEVEL_ACTION = 'GET_WEECHA_LEVEL_ACTION';
export const RECHARGE_USER_BALANCE = 'RECHARGE_USER_BALANCE';
export const GET_RECHARGE_AGENCY = 'GET_RECHARGE_AGENCY';
export const RECONNECT_LIVE_STREAM = 'RECONNECT_LIVE_STREAM';

export const GET_CUSTOMER_SUPPORT_MSG_ACTION =
  'GET_CUSTOMER_SUPPORT_MSG_ACTION';
export const GET_CUSTOMER_MSG_SEND_ACTION = 'GET_CUSTOMER_MSG_SEND_ACTION';

export const HOST_GIFT_INCOME_ACTION = 'HOST_GIFT_INCOME_ACTION';
